# Generated by Django 5.2.6 on 2026-09-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_customer_default_csr_agent_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calllog',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcalllog',
            name='call_duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcalllog',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
