# Generated by Django 5.2.6 on 2026-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_registrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='rice_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rice_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Pending approval'), ('CONFIRMED', 'Confirmed')], default='CONFIRMED', max_length=20),
        ),
    ]
